add_lunch_combo psx_emulator-eng
add_lunch_combo psx_mako-userdebug
add_lunch_combo psx_grouper-userdebug
add_lunch_combo psx_manta-userdebug
add_lunch_combo psx_maguro-userdebug
add_lunch_combo psx_flo-userdebug
